services:
  web: 
    build: 
      # override dockerfile selection
      # context: . 
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
      # something react needs
    environment:
      - CHOKIDAR_USEPOLLING=true